---
- name: Set user.email Git configuration
  command: runuser -l {{ sudo_username }} -c 'git config --global user.email "{{ git_author_email }}"'

- name: Set user.name Git configuration
  command: runuser -l {{ sudo_username }} -c 'git config --global user.name "{{ git_author_name }}"'
...
