---
- name: Copy SSH public key of the new sudo user {{ sudo_username }} to the tmp directory
  fetch:
    src: "/home/{{ sudo_username }}/.ssh/id_rsa.pub"
    dest: "/tmp/id_rsa.pub"
    flat: yes
    fail_on_missing: yes
    validate_checksum: yes

- name: Add the SSH public key of the new sudo user {{ sudo_username }} to root's authorized_keys
  authorized_key:
    user: root
    key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
    state: present

- name: Remove temporary SSH public key file
  file:
    path: "/tmp/id_rsa.pub"
    state: absent

- name: Configure SSH client to automatically accept host key
  lineinfile:
    dest: "/home/{{ sudo_username }}/.ssh/config"
    line: |
      Host localhost
        StrictHostKeyChecking no
    create: yes
    state: present
    owner: "{{ sudo_username }}"
    mode: "0600"
...
