---
- name: Ansible Repo | Check if the ansible_repo_dest directory exists
  stat:
    path: "{{ ansible_repo_dest }}"
  register: repo_dest_status

- name: Ansible Repo | Clone or pull the repository
  git:
    repo: "{{ ansible_repo_url }}"
    dest: "{{ ansible_repo_dest }}"
    version: main
    accept_hostkey: yes
    key_file: "/home/{{ sudo_username }}/.ssh/id_rsa"
    force: yes
  register: pulled_repo
  when:
    - not repo_dest_status.stat.exists

- name: Ansible Repo | Set safe.directory exception for repository directory
  command: git config --global --add safe.directory "{{ ansible_repo_dest }}"
  when:
    - pulled_repo.changed

- name: Ansible Repo | Change owner and group owner of the repository directory and its contents
  when: pulled_repo.changed
  file:
    path: "{{ ansible_repo_dest }}"
    state: directory
    recurse: yes
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    follow: yes
...
