---
- name: Restart System If Needed
  hosts: [servers]
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Check is system needs to restart
      stat:
        path: /var/run/reboot-required
      register: restart_check
      changed_when: false

    - name: Perform system restart if required
      reboot:
        msg: "Reboot initiated by Ansible"
        reboot_timeout: 300
      when: restart_check.stat.exists
...
