---
- name: Print system distribution and version
  hosts: [servers]
  gather_facts: yes
  tasks:
    - name: Print system distribution and version
      debug:
        msg: "Distribution: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"
...
