---
- name: Upgrade System Packages If Needed
  hosts: [servers]
  gather_facts: yes
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - ../vars/global.yml
  tasks:
    - name: Update System Packages for apt-based distributions
      when: ansible_distribution in apt_distributions
      apt:
        upgrade: dist
        update_cache: yes

    - name: Update System Packages for yum-based distributions
      when: ansible_distribution in yum_distributions
      yum:
        name: '*'
        state: latest
        update_cache: yes
...
